### ISSUE TITLE
WDIC: out of bound error

### ISSUE THREAD

**Issue by miurahr** [eb4j/xml2eb#10]
It is happened with erroneous data.
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -4
	at java.lang.String.substring(String.java:1967)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml._makeItemNode(Wdic2Xml.java:585)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml._makeContentNode(Wdic2Xml.java:305)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml.convert(Wdic2Xml.java:158)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml.main(Wdic2Xml.java:98)
```

**Comment by miurahr** [comment]
It seems WdicUtil.indexOf() returns -4. It should return -1 when not-found or  >=0.

**Comment by miurahr** [comment]
6a580335db178 includes interim fix for this.
```
@@ -576,25 +576,27 @@ public class Wdic2Xml {
                     // 定義語 (簡易形式)
                     for (; i < n; i++) {
                         body = bodyList.get(i);
                         block = WdicUtil.deleteTab(body);
                         if (!block.startsWith(":: ")) {
                             i--;
                             break;
                         }
                         int idx = WdicUtil.indexOf(block, "|", 3);
-                        String dt = block.substring(3, idx).trim();
-                        String dd = block.substring(idx + 1).trim();
-                        _appendText(item, indentElem, "\u30fb " + dt);
-                        _appendNewLine(indentElem);
-                        Element indentElem2 = _appendElement(indentElem, "indent");
-                        _appendText(item, indentElem2, dd);
-                        _appendNewLine(indentElem2);
+                        if (idx >= 0) { // return minus when not found
+                            String dt = block.substring(3, idx).trim();
+                            String dd = block.substring(idx + 1).trim();
+                            _appendText(item, indentElem, "\u30fb " + dt);
+                            _appendNewLine(indentElem);
+                            Element indentElem2 = _appendElement(indentElem, "indent");
+                            _appendText(item, indentElem2, dd);
+                            _appendNewLine(indentElem2);
+                        }
                     }
```

**Comment by miurahr** [comment]
WdicUtils may have another bug.
