### ISSUE TITLE
WDIC: out of bound error and Null pointer error

### ISSUE THREAD

**Issue by miurahr** [eb4j/xml2eb#11]
```
java.lang.IndexOutOfBoundsException: Index: 11, Size: 11
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at io.github.eb4j.xml2eb.converter.wdic.WdicTableRow.get(WdicTableRow.java:60)
	at io.github.eb4j.xml2eb.converter.wdic.WdicTable._parseSimple(WdicTable.java:421)
	at io.github.eb4j.xml2eb.converter.wdic.WdicTable._parse(WdicTable.java:286)
	at io.github.eb4j.xml2eb.converter.wdic.WdicTable._makeImage(WdicTable.java:77)
	at io.github.eb4j.xml2eb.converter.wdic.WdicTable.getImage(WdicTable.java:67)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml._makeItemNode(Wdic2Xml.java:711)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml._makeContentNode(Wdic2Xml.java:305)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml.convert(Wdic2Xml.java:158)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml.main(Wdic2Xml.java:98)
10:00:55,613 WARN  [WdicTable] column data unavailable: TECH:TCPERIO:画面解像度
Exception in thread "main" java.lang.NullPointerException
	at io.github.eb4j.xml2eb.util.BmpUtil._convertImage(BmpUtil.java:105)
	at io.github.eb4j.xml2eb.util.BmpUtil.write(BmpUtil.java:58)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml._makeItemNode(Wdic2Xml.java:713)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml._makeContentNode(Wdic2Xml.java:305)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml.convert(Wdic2Xml.java:158)
	at io.github.eb4j.xml2eb.converter.wdic.Wdic2Xml.main(Wdic2Xml.java:98)
```

**Comment by miurahr** [comment]
This  happened when source data is corrupted.

```
|= 名称       |解像度|<     |画素数\\br;(百万)|縦横比|画素数比率|<|<|<|<|<|<
|= ~          |横    |縦    |~   |~         |VGA  |QVGA  |QVGA+ |WQVGA |WQVGA+|HVGA
|| =<<[[QVGA]]|>>320 |>>240 |0.08|4\\ratio;3 |>>25%|=><‐ |>>93% |>>80% |>>75% |>>50%
|| =<<QVGA+   |>>345 |>>240 |0.08|          |>>27%|>>108%|=><‐ |>>86% |>>81% |>>54%
|| =<<WQVGA   |>>400 |>>240 |0.10|5\\ratio;3 |>>31%|>>125%|>>116%|=><‐ |>>94% |>>63%
```

There is verbose "|<" character in first line (row size 12), and other row size is 11.

**Comment by miurahr** [comment]
It should not show stack trace.

**Comment by miurahr** [comment]
Also it should ignore corrupted table but null pointer exception.
